
DROP TABLE USERINFO;
--------------------------------------------------------
--  DDL for Table USERINFO
--------------------------------------------------------

  CREATE TABLE "LATTEWORLD"."USERINFO" 
   (   "USERID" VARCHAR2(50 BYTE), 
   "MINIHOMECODE" VARCHAR2(50 BYTE), 
   "USERPWD" VARCHAR2(50 BYTE), 
   "USERNAME" VARCHAR2(30 BYTE), 
   "USERTYPE" NUMBER DEFAULT 1, 
   "USERSTATUS" NUMBER(1,0) DEFAULT 1, 
   "REGISTERDATE" DATE DEFAULT SYSDATE, 
   "ZAT" NUMBER DEFAULT 100, 
   "REPORTCOUNT" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013611
--------------------------------------------------------

  CREATE UNIQUE INDEX "LATTEWORLD"."SYS_C0013611" ON "LATTEWORLD"."USERINFO" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0013612
--------------------------------------------------------

  CREATE UNIQUE INDEX "LATTEWORLD"."SYS_C0013612" ON "LATTEWORLD"."USERINFO" ("MINIHOMECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table USERINFO
--------------------------------------------------------

  ALTER TABLE "LATTEWORLD"."USERINFO" ADD UNIQUE ("MINIHOMECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LATTEWORLD"."USERINFO" ADD PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "LATTEWORLD"."USERINFO" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "LATTEWORLD"."USERINFO" MODIFY ("USERPWD" NOT NULL ENABLE);