/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-11-09 06:20:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/promo/Desktop/FinalProject/LatteWorld/web/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1573049096098L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>라떼는</title>\r\n");
      out.write("<style>\r\n");
      out.write("*{\r\n");
      out.write("margin : 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("div{\r\n");
      out.write("\tborder : 3px solid black;\r\n");
      out.write("\tmargin : 5px;\r\n");
      out.write("}\r\n");
      out.write("#mainTop{\r\n");
      out.write("\twidth : 85%;\r\n");
      out.write("\theight : 10%;\r\n");
      out.write("}\r\n");
      out.write("#mainTop *{\r\n");
      out.write("\tdisplay : inline-block;\r\n");
      out.write("}\r\n");
      out.write("#mainLeft{\r\n");
      out.write("\theight : 80%;\r\n");
      out.write("\twidth : 15%;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tleft : 0%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mainCenter{\r\n");
      out.write("\theight : 80%;\r\n");
      out.write("\twidth : 70%;\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tleft : 15%;\t\r\n");
      out.write("}\r\n");
      out.write("#mainCenter > div {\r\n");
      out.write("width : 99%;\r\n");
      out.write("}\r\n");
      out.write("#goodMessage{\r\n");
      out.write("\twidth : 98%;\r\n");
      out.write("\theight : 30%;\r\n");
      out.write("}\r\n");
      out.write("#search{\r\n");
      out.write("width : 98%;\r\n");
      out.write("height : auto;\r\n");
      out.write("}\r\n");
      out.write("#search *{\r\n");
      out.write("\theight : auto;\r\n");
      out.write("\tdisplay : inline;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#centerBottom {\r\n");
      out.write("height : 63%;\r\n");
      out.write("width : 98%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#centerBottom * {\r\n");
      out.write("display : inline-block;\r\n");
      out.write("width : 40%;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#centerBottomLeft {\r\n");
      out.write("position : relative;\r\n");
      out.write("width : 48%;\r\n");
      out.write("height : 98%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#todayNews{\r\n");
      out.write("width : 98%;\r\n");
      out.write("height : 48%;\r\n");
      out.write("}\r\n");
      out.write("#todayHomepage{\r\n");
      out.write("width : 98%;\r\n");
      out.write("height : 22%;\r\n");
      out.write("}\r\n");
      out.write("#todayMember{\r\n");
      out.write("width : 98%;\r\n");
      out.write("height : 22%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#centerBottomRight{\r\n");
      out.write("position : relative;\r\n");
      out.write("width : 48%;\r\n");
      out.write("height : 98%;\r\n");
      out.write("top : -10%;\r\n");
      out.write("}\r\n");
      out.write("#centerBottomRight *{\r\n");
      out.write("display : block;\r\n");
      out.write("width : 98%;\r\n");
      out.write("height : 31%;\r\n");
      out.write("}\r\n");
      out.write("#goodMessageImg{\r\n");
      out.write("height : 220px;\r\n");
      out.write("width : 200px;\r\n");
      out.write("}\r\n");
      out.write("#leftMenuBar{\r\n");
      out.write("height : 65%;\r\n");
      out.write("}\r\n");
      out.write("#leftMenus{\r\n");
      out.write("height : 48%;\r\n");
      out.write("}\r\n");
      out.write("#addLeftMenus{\r\n");
      out.write("height : 48%;\r\n");
      out.write("}\r\n");
      out.write("#findZone{\r\n");
      out.write("position : relative;\r\n");
      out.write("height : 30%;\r\n");
      out.write("top : 35%;\r\n");
      out.write("}\r\n");
      out.write("#leftLogin{\r\n");
      out.write("height : 29%;\r\n");
      out.write("}\r\n");
      out.write("#join{\r\n");
      out.write("cursor : pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 메인 탑 메뉴 -->\r\n");
      out.write("\t<div id = \"mainTop\">\r\n");
      out.write("\t\t<div id = \"topLogo\">\r\n");
      out.write("\t\t\t<img id = \"mainLogo\" width = \"80px\" height = \"80px\" src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/images/MainLogo.jpg\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"topMenu\">\r\n");
      out.write("\t\t\t<span><a>미니홈피</a></span>\r\n");
      out.write("\t\t\t<span><a>선물가게</a></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"topIcon\"  style = \"float : right\"><input type = \"button\" value = \"BGM 상점\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<!-- 메인 왼쪽 메뉴  -->\r\n");
      out.write("\t<div id = \"mainLeft\">\r\n");
      out.write("\t\t<div id = \"leftLoginBox\">\r\n");
      out.write("\t\t\t| LATTE WORLD\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\t\t\r\n");
      out.write("\t\t<div id = \"leftMenuBar\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id = \"leftMenus\">\r\n");
      out.write("\t\t\t\t<p>서비스 미리보기</p>\r\n");
      out.write("\t\t\t\t<p>라떼 월드란?</p>\r\n");
      out.write("\t\t\t\t<p>미니 홈피란?</p>\r\n");
      out.write("\t\t\t\t<p>클럽이란?</p>\r\n");
      out.write("\t\t\t\t<p>등등등</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id = \"addLeftMenus\">\r\n");
      out.write("\t\t\t\t<p>명예 회손 신고 센터</p>\r\n");
      out.write("\t\t\t\t<p>클린 라떼</p>\r\n");
      out.write("\t\t\t\t<p>잣 사기</p>\r\n");
      out.write("\t\t\t\t<p>이달의 페이퍼</p>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 센타 부분 -->\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"mainCenter\">\r\n");
      out.write("\t\t<div id = \"goodMessage\">\r\n");
      out.write("\t\t<img src = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/images/mainContent.jpg\" height = \"200px\" width = \"500px\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div id = \"search\">\r\n");
      out.write("\t\t\t<select id = \"searchMenu\">\r\n");
      out.write("\t\t\t\t<option value = \"all\">전체검색</option>\r\n");
      out.write("\t\t\t\t<option value = \"title\">제목</option>\r\n");
      out.write("\t\t\t\t<option value = \"content\">내용</option>\r\n");
      out.write("\t\t\t\t<option value = \"writer\">작성자</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t<input style = \"width : 350px\" id = \"searchContent\" placeholder = \"라떼는 이렇게 검색헀어...!\">\r\n");
      out.write("\t\t\t<button id = \"searchBtn\"> 찾 기 </button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id = \"centerBottom\">\r\n");
      out.write("\t\t\t<div id = \"centerBottomLeft\">\r\n");
      out.write("\t\t\t\t<div id = \"todayNews\">라떼는 이런게 핫했다!</div>\r\n");
      out.write("\t\t\t\t<div id = \"todayHomepage\">오늘의 홈페이지</div>\r\n");
      out.write("\t\t\t\t<div id = \"todayMember\">오늘의 핫피플</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id = \"centerBottomRight\">\r\n");
      out.write("\t\t\t\t<div id = \"todayWriter\">최고의 글</div>\r\n");
      out.write("\t\t\t\t<div id = \"purchase\">선물가게</div>\r\n");
      out.write("\t\t\t\t<div id = \"events\">이벤트</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\tfunction register(){\r\n");
      out.write("\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/views/common/userJoin.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/common/mainPage.jsp(142,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.user }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div id = \"leftLogin\">\r\n");
          out.write("\t\t\t\t<form action =\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/LoginServlet\" method = \"post\">\r\n");
          out.write("\t\t\t\t\t<table>\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>이메일</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td><input type = \"text\" size = \"10px\" name = \"userId\"></td>\r\n");
          out.write("\t\t\t\t\t\t\t<td rowspan = \"2\"><button>Login</button></td>\r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t<td>비밀번호</td>\r\n");
          out.write("\t\t\t\t\t\t\t<td><input type = \"password\" size = \"10px\" name = \"userPwd\"></td>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t<div id = \"findZone\">\r\n");
          out.write("\t\t\t\t\t\t? <label id =\"findIdPw\">이메일 / 비밀번호 찾기</label><br>\r\n");
          out.write("\t\t\t\t\t\t? <label id =\"join\" onclick = \"register()\">회원 가입하기</label>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t</form>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /views/common/mainPage.jsp(164,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.user}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t<div id = \"leftLogin\">\r\n");
          out.write("\t\t\t\t<img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/views/images/pic1.jpg\"height = \"130px\" width = \"100px\"><br>\r\n");
          out.write("\t\t\t\t<h3> ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다 :)</h3>\r\n");
          out.write("\t\t\t\t<button id = \"myPage\">마이 페이지</button>\r\n");
          out.write("\t\t\t\t<button onclick = \"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/LogoutServlet'\">로그아웃</button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
